UCF/Search-Service-Django

programs/management/commands/import-catalog-data.py
requirements.txt

Updates `get_description()` to more broadly strip undesired namespaces from program catalog markup.
Specifically, this update strips `xmlns` attributes from the catalog xml before we attempt parsing it--doing so auto-magically strips namespace information from the parsed xml data (e.g. `<a:ul>` becomes `<ul>`).  From there, we assume the catalog description parts we care about are parseable html, and pass that parsed markup to BeautifulSoup to parse it as such.  We then loop through that html and remove non-whitelisted elements (because the catalog data includes vendor-specific markup, such as `<permalink>`).
I am open to suggestions on better ways of removing non-whitelisted elements (for the life of me, I couldn't get the `unwrap()` method to work properly in that first node loop), or …

Program description namespace removal - revisited

---

programs/fixtures/programs.json
programs/management/commands/import-programs.py
programs/models.py

Enhancements:
* Added ability to override college assignment internally using the `CollegeOverride` model.
* Added logic to the program importer to use internal mappings if the `--use-internal-mapping` flag is set. The `--mapping-path` variable will be left in place for backwards compatibility.
* Updated the initial `programs.json` fixture to include the college mappings we currently have in our mappings file.
* Added `CollegeManager` class to make importing fixtures easier. The `get_by_natural_key` function makes it possible to add a college to a fixture using its `short_name` value instead of having to provide the `PK` which can vary from environment to environment.

Program import updates

---

programs/serializers.py

Added ID field to related program serializer to display IDs for subplans + parent programs in API results.

ID field for result parent programs/subplans

---

programs/management/commands/import-catalog-data.py

- Added check to `get_catalog_programs` to ensure we're only importing active catalog degree data
- Updated `match_programs` to always remove an existing catalog description on all programs before importing fresh data

Removal of stale catalog data

---

teledata/models.py

Enhancements:
* We're now adding together the expressions that generate the scores, instead of creating a separate field for each score and adding the fields together. This should increase the efficiency of the query.
* Corrected issues with the `When` statements, especially related to `__contains` conditions by removing the `Value()` functions wrapped around the `search_query` variable.

Updated query to properly execute like statements

---

teledata/admin.py
teledata/models.py

Enhancements:
* Limited number of entries in the `Content type` field for keywords. The dropdown is limited now to the 3 content types that keywords actually effect.
Bug Fixes:
* Corrected bug that occurs when there is more than 1 object in the `CombinedTeledata` data with the same `object_id` - which is allowable and a pretty normal occurrence.

Keywords fix

---

requirements.txt
settings.py
teledata/pagination.py
teledata/views.py

Bug Fixes:
* Adds the `resultCount` count field to pagination on the CombinedTeledata - `/api/v1/teledata/` - view for backwards compatibility.
* Adds the CORS middleware package so that the feeds can be consumed by client-side applications.

Hot Fix CORS and Pagination

---

programs/management/commands/import-programs.py

Imports CIP codes for parent-level programs.  Resolves #52.
Note that we are intentionally _not_ adding CIPs to subplans because subplans don't have explicit CIP values in APIM's data, and there are instances where a parent plan's CIP may not be correct/accurate for its subplans.

CIP imports

---

teledata/views.py

Bug Fixes:
* Fixes #56. When no query is made, the order by logic fails because the `score` field is added dynamically. To fix this, the results are ordered by `score` only when a search query is made, and ordered by id when an empty set is being returned.

Updated combined search view to order by id when no query is made

---

programs/serializers.py
programs/urls.py
programs/views.py

Enhancements:
* Removes outcomes, projection totals and careers from the program serializer and instead creates separate feeds for each which can be accessed underneath the program detail view, i.e. `/api/v1/programs/<id>/outcomes/`.
* A link to each view has been added to the programs serializer.

Simple feed

---

core/models.py
images/management/commands/import-tandemvault-images.py
images/management/commands/import-tandemvault-tags.py

Added an importer for existing tags and their synonyms from Tandem Vault.  Tag data must be downloaded manually from the Tandem Vault admin and passed to the import command.
Resolves #81

Tag importer

---

images/management/commands/import-tandemvault-images.py
images/management/commands/import-tandemvault-tags.py

Fixed issues with looking up existing ImageTags in the image importer and Tandemvault tag importer that could result in duplicate tags being returned unexpectedly.

Duplicate tag fixes

---

images/management/commands/import-tandemvault-images.py
images/management/commands/import-tandemvault-tags.py

- Added argument for allowing stale images to be preserved during the image import (by default, existing Image objects not present in the retrieved Tandem Vault data will be *deleted*).
- Added argument that deletes stale tags after the import finishes (by default, tags assigned to an image, and synonyms whose root tag is assigned to an image are *preserved*)
- Removed option to delete tags during the Tandem Vault tag importer, since we only ever want to delete stale tag data after images have been processed
Resolves #99

Stale image/tag object deletion

---

images/management/commands/import-tandemvault-images.py
images/management/commands/import-tandemvault-tags.py

- Various linter improvements and updates to string printing and formatting to be more python3-ready
- Added a few terms to the image auto-tagging blacklist and alphabetized it
- Un-commented out the main pagination loop in the image importer's `process_images()`, so that we can perform an actual full import

Image importer cleanup

---

images/models.py
images/serializers.py
images/views.py

See title.  Should help ensure queries for exact tag, location, and caption matches rank higher than just substring matches.
This PR also removes searching by filename, since 99% of filenames are pretty useless/irrelevant.

Implemented basic scoring system for image search results

---

programs/management/commands/process-profiles.py
programs/models.py
programs/serializers.py
settings_local.tmpl.py

* Adds a `profile` field, which provides a scalar value for a program profile.
* The `profile` field is populated with the URL of either the `primary` profile, the primary profile has determined by the `PROGRAM_PROFILE` logic, or the URL of the primary `ProgramProfileType` as determined by the same logic if there is no profile.
* Adds a process for assigning the `primary` attribute on profiles based on the `PROGRAM_PROFILE` logic.

Single profile field

---

programs/management/commands/import-programs.py

Fixed bug during the program import when we attempt to remove existing current-CIP relationships and pass in `code=data['CIP']` unnecessarily to the CIP queryset.

Program import hotfix

---

core/urls.py
core/views.py
requirements.txt
settings.py
settings_local.tmpl.py
templates/base.html
templates/login.html
templates/logout.html
templates/search.html
urls.py

Places basic local Django authentication in front of Archimedes.
As part of this update, Archimedes has been moved from /search/ to /manager/search/ as a quick workaround for Varnish issues.  If having the URL at /search/ is critical for distribution to alpha testers, we can look into working with Tim's team to update the vcl to accommodate, but for now, this is our quickest option to get the repo to a tag-able state.

Basic front-end authentication for Archimedes

---

teledata/filters.py
teledata/serializers.py
teledata/views.py
templates/home.html

Updates that facilitate support for Map shifting to using the Django Search Service for retrieving teledata instead of the old PHP search service.
- Added ability to order organizations, departments, and buildings views by name (as well as ID).  The combined teledata view is also sortable by `sort_name` now.
- Added `id` and `import_id` to `OrganizationBriefSerializer`, since Map depends on the `import_id` value being available on nested orgs in the departments list view.  `id` is added for clarity/to differentiate between the two values and for consistency with the `BuildingSerializer`.
- Added ability to filter the departments list by org `import_id`.

Teledata - Map compatibility updates

---

teledata/pagination.py
teledata/views.py

- Updated `CombinedTeledataSearchView` to _not_ fetch search results if the `search` param is present, but empty, for consistency with the old search service
- Updated `BackwardsCompatiblePagination` class to extend from `LimitOffsetPagination` to add `limit` query param support to the combined teledata search.

Teledata search option updates/fixes

---

programs/management/commands/import-programs.py

- Removed an errant comma in the program import's `print_results()`.
- Updated program is_valid logic to ensure we only check active locations against undergraduate programs that are not minors or certificates.

Hotfixes (typo; invalid program logic adjustments)

---

teledata/models.py

Updated CombinedTeledata's `update_data()` to utilize building `import_id`s instead of their PKs in the search service.  Fixes incorrect building numbers in the teledata search endpoint.

Fixed building IDs on CombinedTeledata

---

images/management/commands/import-tandemvault-images.py

This scenario shouldn't be happening, but in cases where it does happen anyway, I've added an exception to just skip the result instead of erroring out.

Tandemvault import - added exception handling when multiple images with source ID are found

---

images/management/commands/import-tandemvault-images.py
images/management/commands/import-tandemvault-tags.py

Fixed a few outlying bugs in the updated tandemvault image and tag importers (incorrect variable/key names; string encoding differences between Python 2/3.)

A few more Tandemvault tag + image import fixes

---

programs/admin.py

Big Fixes:
* Marking the program list output as safe so it isn't escaped by Django and properly displays as HTML:

Application Deadline Admin View Big Fix

---

programs/management/commands/import-catalog-data.py

Updated the catalog importer to load in a complete catalog description by grabbing the HTML contents of each program's catalog URL.
One thing to note--the full catalog descriptions have all `<a>` tags removed; this is intentional and was requested by Roger.
Further sanitization and cleanup of catalog markup will be included in a future PR.

Programs - full catalog description import

---

programs/management/commands/import-catalog-data.py
settings_local.tmpl.py

- Updated the catalog import to accept a new `--program-ids` arg, which accepts a list of program pk's that should be processed (instead of processing all undergrad or all grad programs)
- Added new catalog-related settings to settings_local.py that are necessary for by-program catalog imports to work, and allow us to reduce the number of required params to pass to the import command.

Catalog description imports by program ID

---

programs/management/commands/import-catalog-data.py
programs/utilities/content_node.py

- Modified how `__list_processing()` performs regex matching against list items so that complete `<li>`s are processed as individual lines, instead of using `self.cleaned.splitlines()` which can split lists in unexpected ways depending on inner elements and newline usage.
- Updated the importer to allow `dl`, `dt` and `dd` elements.

Catalog import - list processing improvements

---

programs/management/commands/import-catalog-data.py
programs/utilities/content_node.py

- Made updates to the importer's `sanitize_description()` to better handle characters in descriptions we don't want.  Ensuring we strip garbage characters appropriately helps improve contact info matching and scoring.
- Updated the `ContentNode` class to store cleaned node text in two separate fields--one that stores all text content in a single string (`self.cleaned_str`), and another that stores them in a list per-line (`self.cleaned_lines`).  Doing this avoids the need to repeatedly split the cleaned markup in various functions, and using `soup.stripped_strings` instead of `soup.get_text(separator='\n').strip()` should be more accurate and trims each line + eliminates empty string nodes.
- Added basic string and regex matching for individual ContentNode lines to detect common types of …

Catalog import - contact info extraction improvements

---

programs/utilities/content_node.py
programs/utilities/oscar.py

Ported over some updates present in the `single-description-fetch` I want to make sure are included with these importer updates, regardless of whether or not I'm able to finish that feature:
- Updated the course matching regex in `ContentNode.__list_processing()`
- Added node initializer to Oscar

Catalog import - extraneous updates from single-description-fetch

---

programs/management/commands/import-catalog-data.py
programs/utilities/content_node.py

- Removed `ContentNode.lines`, as it doesn't appear to be in use
- Removed unused `LIST_ITEM` content node type and related logic
- Fixed an existing issue when importing (short) graduate catalog descriptions that could result in unwanted content being included in the final description markup

Catalog import - Misc. fixes/cleanup

---

programs/utilities/content_node.py
programs/utilities/oscar.py

- Added properties to the `ContentNode` object that store the node's subheadings and next sibling headings.
- Updated Oscar to more accurately increment and re-assign heading tags based on previous headings' known subheadings and sibling headings.

Catalog import - heading order

---

programs/management/commands/import-catalog-data.py
programs/utilities/content_node.py
programs/utilities/oscar.py

- Miscellaneous bugfixes:
- Ensure empty `ProgramDescription` objects aren't created if a retrieved/sanitized description string is empty.
- Added failsafe for division by zero when calculating average contact info scores for a node.
- Updated Oscar to ignore top-level `<br>` tags (`<br>`s within paragraphs remain intact).
- Added note and filtering of garbage characters that likely result from mismatched character encodings.
- Contact info extraction fine-tuning:
- Added `PERSON` to allowed `PII_TYPES` for contact info extraction (Comprehend's base entity detection API labels things that look like person names as `PERSON`, unlike the PII entity detection, which uses `NAME`.)
- Added more string matches and regex checks for lines that look like blocks of contact info.

Catalog import - More bugfixes and fine-tuning

---

programs/management/commands/import-catalog-data.py
programs/utilities/oscar.py

Fixes and improvements to catalog description content sanitization:
- Added logic that translates double line breaks (`<br><br>`) into individual paragraphs.
- Before: `<p>abc<br><br>def</p>`
- After: `<p>abc</p><p>def</p>`
Helps resolve issues with some contact info in catalog descriptions bleeding into the first paragraph of the description's introduction, and ensures those chunks are filtered for contact data separately.
- Added logic that removes nested like elements.
- Before: `<em>abc<em>def</em></em>`
- After: `<em>abcdef</em>`
This helps reduce the likelihood of poorly-formatted markup impacting how lines of text within nodes are determined, thus improving the accuracy of contact data filtering.
- Added logic that removes inline elements, like `<em>` and `<strong>`, that …

Catalog content filtering improvements

---

programs/management/commands/import-catalog-data.py

Fixed the catalog description sanitization step to account for heading `match` nodes with multiple children (where `match.string` is `None`)

Hotfix - better handle node sanitization for headings with no .string value

---

programs/management/commands/import-catalog-data.py

Wrapped logic that attempts to locate the short catalog description for a degree in a try-catch and back out early upon erroring to better handle potentially malformed catalog XML.

Catalog import - short catalog description parsing hardening

---

programs/management/commands/import-catalog-descriptions.py
settings_local.tmpl.py

Adds an alternate catalog importer, `import-catalog-descriptions`, that imports catalog data from the new Kuali system.  Functionally this is about the same as the existing `import-catalog-data` importer, but doesn't require outbound GET requests for every short and full description, and no longer expects data to be coming from separate catalogs (undergraduate and graduate data is all processed at the same time).

Kuali catalog importer

---

programs/management/commands/import-catalog-descriptions.py

- Added an option to `sanitize_description()` in the catalog importer to remove tables from the passed in description string.  Also updated references to 'strip' vs 'unwrap' for clarification.  Short catalog descriptions now use this option in order to remove metadata tables at the top of all graduate catalog descriptions.
- Fixed retrieval of program descriptions on catalog tracks, which are stored in `description` fields rather than `programDescription`

Removal of tables from short catalog descriptions; fixed retrieval of program descriptions on tracks

---

programs/management/commands/import-catalog-descriptions.py

See title.  Existing logic was allowing cells in application deadline tables in the full catalog descriptions to be removed completely, resulting in incorrect cell assignment per column for other cells with content.  Allowing empty table cells ensures cell ordering is preserved.

Allow tables in description content to have empty td, th cells

---

programs/management/commands/import-catalog-descriptions.py
programs/utilities/catalog_match.py

- Updated the catalog importer to support new structured fields in Kuali for more discrete chunks of curriculum-related content.  `CatalogEntry.curriculum` has been modified to return a combination of these new fields if they're in use, or to continue to return the `requiredCoreCourses` field value if not.
- To support the bullet point above, a new fetch for all catalog IDs has been added (`__get_catalogs()`) early in the import process, as well as calls to per-program endpoints for pre-generated HTML (intended for Kuali's frontend, which we're borrowing for degree requirements in the big "curriculum" block).  I'm open to suggestions on how to re-work where this fetch occurs and potentially implement threading for a future PR.
- Updated `__sanitize_description()` to better support HTML …

Initial structured catalog data support

---

programs/management/commands/import-catalog-descriptions.py
programs/utilities/content_node.py
programs/utilities/oscar.py

JSON fetch hardening (`__get_json_response()`):
- Added request timeout of 15s to `__get_json_response()`
- Added `response.raise_for_status()` in the main `try` block to ensure an actual `HTTPError` can be caught when one occurs.  Previously, the only error you'd see logged would be related to `response.json()` bombing, due to 400/500 errors not returning JSON-like content.
- Updated `__get_json_response()` to re-try fetching data if an initial fetch failed.  Kuali's front-facing endpoints notoriously return intermittent 502s; this update should give us the best chance at avoiding data loss due to these random errors.
- `__get_json_response()` will now always return _something_, even if it's `None`.
Removal of display-related content from descriptions:
- Added the `DISPLAY` …

Catalog importer - JSON fetch hardening; removal of display-related content from descriptions

---

programs/utilities/catalog_match.py

- Updated catalog importer to exclude degree requirements in curriculum/'full' descriptions if Kuali failed to generate a valid lists of courses in its HTML data endpoint

Catalog import - exclude malformed degree requirements

---

research/serializers.py
teledata/serializers.py

Enhancements:
* Added a new simplified serializer for staff records that only includes email and phone.
* Updated the serializer used for the `teledata_record` field on the `ResearcherSerializer` to use the simplified version.

Staff Serializer

---

research/models.py
research/serializers.py
units/models.py
units/serializers.py

Resolves #284.
Adds `ext_employee_id`, `first_name`, `last_name`, `prefix`, `department`, `organization`, `division`, and `college` information to `employee_record` for each researcher on the researchers API endpoint. Also uses the name property to display the units models names in the admin so that display_names can be used if present.

Adds employee information to researchers API endpoint

---

research/serializers.py

Enhancements:
* In order to limit the number of results we pull into the WordPress site, this limits the research terms returned to the top 10 terms based on assignment.

Limit Research Terms

---

research/serializers.py

- Added a new `research_terms_featured` field to Researcher API results, which provides a more filtered set of research terms suitable for importing into WordPress.  Currently, these featured terms are limited to terms at least two characters long.
- Updated sorting of researcher terms to perform sorting after fetching, since `obj.research_terms.annotate(researcher_count=Count('researchers'))` was returning the number of times the given term was assigned to _that researcher_, and not to _all researchers_ (and would always return 1).

Featured research terms; fixed sorting of research terms by researcher count

---

research/serializers.py
research/urls.py
research/views.py

Enhancements:
* To simplify the primary researchers view, `research_terms` is now being hyperlinked to specific view which lists all of the research terms for a specific researcher: `/research/researcher/<id>/terms/`. This should reduce the amount of data needed to represent each record, while still providing a place to retrieve the information.

Research Term View

---

research/serializers.py

Enhancements:
* Adds additional meta data to the researcher record on each published work. Instead of just the internal ID, the ID, ORCID, formatted name, formatted name with title _and_ most importantly the employee ID are listed. This will allow us to match up related researchers when importing into WordPress.

Added serializer for researchers that includes some basic information

---

programs/models.py

Bug Fixes:
* It's possible for an academic term to be entered in our source system that does not match the required schema of `<Semester> <Year>`, so this checks to make sure the split full name has two elements before trying to access it. If it does not, we assume it's a nonsense value and return the year 9999 as the start term.

Academic Term Nonsense

---

programs/models.py
programs/serializers.py
settings_local.tmpl.py

Enhancements:
* Adds the `excerpt` field to programs.
* Adds a setting for determining which program description should be used to generate the excerpt.
* Adds the `excerpt` field to the program serializer.
Note:
* We may need to come up to cache the excerpt so we're not having to generate it on the fly each API call. It would be nice to do some benchmarking to see how much this is slowing down the API calls compared to QA/PROD.
* We also may need to make the number of words configurable.

Description Excerpts

---

programs/utilities/catalog_match.py

Bug Fixes:
* Currently, it is possible for program to match with catalog entries from previous years. As a temporary fix, we are now getting the best match, then filtering all catalog entries to only those with the same `code` value as the best match, and then choosing the match with the most recent created date.

Better Catalog Matches

---

dev-requirements.txt
programs/admin.py
programs/management/commands/import-career-weights.py
pyproject.toml

Enhancements:
* Readded `spacy` to the dev-requirements.txt
* Updated the `import-career-weights` command to accept a different set of fields for explicitly setting the weight on Weighted Job Positions (Careers).
* Added an additional control flag, `--keep-existing` which will override the default behavior of deleting all existing weighted job positions prior to importing.

Weighted Career Importer Updates

---

programs/serializers.py

In our recently added `subarea_of_interest` field, CIPs that have single digits for their subarea, i.e. `02`, `03`, etc., were not being returned when queried. The string format we were using wasn't taking into account the fact that those numbers need to be zero padded. So for example, the Accounting (BSBA) program has a CIP of `52.0301`. When the string was formatted, it was looking up a code of `52.3` instead of `52.03`. I've corrected this by casting the subarea to a string, and then calling the `zfill` (zero fill) function and specifying it should have a length of 2 digits.
Changes can be reviewed in DEV by looking at program ID 2.

Lookup Bug

---

programs/models.py
programs/serializers.py

All of the subcodes (area, subarea, and the precise codes) need to be zero padded. So I went ahead and created 3 new properties to return those properly zero padded and as strings, and updated our view to use these new properties.

Another quick fix to CIP processing

---

programs/utilities/catalog_match.py

Enhancements:
* Added logic that allows programs to be matched to catalog entries by plan_code first before resorting to fuzzy string matching.

Updated to match using plan code when possible

---

programs/management/commands/import-catalog-descriptions.py
programs/utilities/catalog_match.py

Enhancements:
* Updated logic to write the plan code or subplan code from catalog entries (depending on if it's a program or specialization object) and then loop back through and add the plan code to items that only had a subplan code. This then allows us to accurately match subplans to their catalog entries.

Updated catalog import to include subplan code as a matchable field

---

core/filters.py
templates/dashboard/program-list.html

Enhancements:
* Added search and college filter fields.

Program search

---

core/urls.py
core/views.py
settings_local.tmpl.py

- Added logic to scrape the first page titles and URLs from https://jobs.ucf.edu/jobs/search. (title, externalpath)
- Registered the REST API gateway at http://{domain}/api/v1/positions/.
- By default, it returns the 10 latest jobs when using the [ucf-jobs] shortcode in WordPress.
- We are able to receive offset and limit parameters; by default, offset is set to 0 and limit is set to 10.

Positions scraper

---

programs/models.py

Our data model for `Program`s includes a property called `current_cip` that is supposed to return the (singular) `CIP` for a program based on what the current CIP version we're using is. Our various imports and processes are supposed to ensure there is only 1 CIP assigned for each version at a time. However, there seems to be a loophole somewhere, and the property had no logic to account for if there were multiple CIPs assigned for a particular version.
This pull request remedies that by returning `None` if multiple CIPs are returned. In a future pull request, we'll either adjust the model to only allow one CIP per version - possibly by creating a compound unique key - or try to track down the loophole and close it.

Current CIP Property Bug

---

programs/utilities/catalog_match.py

I've updated our matching logic to:
- Reject all catalog descriptions that don't have the `dateStart` field. This should weed out most of the older descriptions, and also is just necessary as there's no other way to tell if a description is current.
- When filtering down the candidates, I reject any descriptions who's `dateStart` is greater than today. This should remove any catalog entries for future catalogs that are not yet published.
- I then ask for the max `dateStart` value available in the remaining candidates. This should give us the _most recent_ catalog entry, that's not a future entry.

Catalog Matching Logic Update

---

marketing/models.py
marketing/parsers.py
marketing/serializers.py
marketing/urls.py
marketing/views.py
urls.py

- Renamed the `titles_formatted` field to `source_formatted` which returns the source and titles formatted for HTML.
- Adds the Quote API endpoints. I will be fully documenting the API in this pull request for review. We will eventually need to put this documentation into the home page or find some other place to document the API.
For some of the following examples, you will need to provide an API key in the request. The easiest way to provide this key is to pass it as a query parameter:
`https://<search-service-url>/api/v1/marketing/quotes/?key=yourreallylongapikey`
Additionally, the `Content-type` header for most of the requests will be `application/json`, but for the create and update views, when passing a file, the `Content-type` needs to be set to `multipart/form-data`. I will …

Added API endpoints for CRUD operations on quotes

---

teledata/filters.py
templates/home.html

- Added the `from_table` field to the teledata filter so that we can use the built-in `__in` filter to search through multiple tables.
- Kept the `use` filter, since it is documented and needs to be kept for backwards compatibility just in case someone is using this API.
- Updated the documentation to reflect the new field.

Teledata Filter Adjustments
