- programs/filters.py
Enhancements:
* If subplan_code is null, the correct record can be pulled up by pass `subplan_code__isnull=True` in the query parameters.
> Added  filter.

- programs/management/commands/import-catalog-data.py
Enhancements:
* Added additional logic that accounts for the differences between undergraduate and graduate descriptions.
* Updated url structure for catalog profiles.
> Hf catalog url update

- programs/management/commands/import-catalog-data.py
Bug Fixes:
* Removes control characters from the description before saving.
> Added line to remove illegal ascii characters

- programs/management/commands/import-programs.py
Bug Fixes:
* Updated the import logic to remove ampersands and replace them with `and` instead.
> College name fix

- programs/management/commands/import-programs.py
Enhancements:
* Adds an additional check for a "Z code" when setting the online flag for programs.
> Online fix

- requirements.txt
Bug Fixes:
* Upgrading Django to 1.11.15 to ensure latest security patches are applied.
> Upgraded to django 1.11.15

- programs/management/commands/import-tuition.py
Bug Fixes:
* Small fixes to the import to generate more accurate counts and remove unnecessary code.
> Mapping fix

- programs/serializers.py
- programs/views.py
- requirements.txt
- settings.py
Enhancements:
* Added ability to filter by field or fieldset on the Programs serializer. This allows for specific fields, or a predefined set of fields. Currently there is only the `identifiers` fieldset defined for Programs.
> Dynamic fields

- programs/filters.py
- programs/management/commands/import-programs.py
Enhancements:
* Added active flag to Program filter class
Bug Fixes to new Enhancements:
* Added the college and department cleanup setup to the subplan import
* Added count processing to the subplan import
> I Fixed It!

- programs/management/commands/import-programs.py
Enhancements:
* Added logic to track which programs are listed in APIM, but are marked as inactive (`active == False`) in our data. This should make it easier to start reporting to IKM what data is still showing up in the feed that is no longer valid.
> List inactive

- teledata/models.py
Enhancements:
* Created the `MatchAgainst` expression which allows for full-text search expressions to be used without having to use `RawSQL` or `.extra` calls.
* Removed `RawSQL` statement for scoring queries with a multi-step annotation system.
> Optimized search

- programs/management/commands/import-program-outcome-data.py
Adds missing protocol param to `ssl.SSLContext()`.
> Outcome data fetch fix

- programs/serializers.py
- programs/urls.py
- programs/views.py
Enhancements:
* Adds serializer for CIPs and three views:
* List view: `/cips/`
* Detail view (default version): `/cips/<code>/`
* Detail view (specify version): `/cips/<code>/<year>/`
* Adds a default limit of 25 CIP records and a max limit of 50.
> CIP Serializer

- teledata/management/commands/import-teledata.py
Ensuring that email is lowercased before importing into the search service.
> Lowering email before importing

- images/models.py
- images/serializers.py
Updated `ImageSerializer` to explicitly define fields and display tags with synonyms.
Resolves #89
> Frontend synonyms

- teledata/models.py
Enhancements:
* Adds the ability to lookup teledata records based on phone number, full or extension.
> Added logic for searching by phone number

- images/management/commands/import-tandemvault-images.py
> Ensure the tandemvault image importer only processes images

- templates/home.html
- Added documentation for the image search view
- Added some missing info about data sources for program employment data under "Data Sources"
> Image search docs

- programs/management/commands/import-profiles.py
* Created a process that allows profiles to be exported from any site using the `UCF-Degree-CPT-Plugin` with the `degrees` API endpoint enabled.
> External Profile Import

- teledata/models.py
> Fixed CombinedTeledataManager email score to compare against email field instead of phone

- programs/serializers.py
> Added 'active' field to ProgramSerializer

- programs/management/commands/import-programs.py
Updated is-online checks during the program import to check against plan/subplan code name for "online", since it's possible for a program coming from APIM to not have the "UCFOnline" flag set, but still have a program name that designates it as an online program.
> Program import - check plan/subplan names for "online" when flagging online programs

- programs/serializers.py
- programs/urls.py
- programs/views.py
Added new API view for program application data, and added a link to it from programs.
Resolves #163.
> Deadline serialization

- programs/management/commands/import-programs.py
Workaround for an issue with urllib2 regarding certificate verification.
> Replaced urllib2 with requests lib in program import

- programs/management/commands/import-catalog-data.py
- programs/management/commands/import-profiles.py
- programs/management/commands/import-tuition.py
- teledata/management/commands/import-teledata.py
All importers modified in this PR have been run + verified in Dev.
> Replaced remaining usage of urllib2 in the project with the requests lib

- programs/management/commands/import-cip.py
Enhancements:
* Created an CIP importer. Does exactly what is sounds like.
> Created a CIP Importer

- programs/management/commands/import-catalog-data.py
- programs/utilities/content_node.py
- programs/utilities/oscar.py
- requirements.txt
Enhancements:
* Introduced the `Oscar` and `ContentNode` classes to help parse through and identify paragraphs, titles, lists and tables within degree descriptions, categorize, as best as possible, the content contained within them, and them reformat or discard them as desired.
* `Oscar` utilizes the Amazon AWS Comprehend API to do some basic language processing on `CONTENT` nodes to try to determine if the nodes should be categorized as content info, or other categories.
* Consolidated markup sanitization logic between `get_description()` and `get_description_full()` for consistency/DRY-er code (`sanitize_description()`)
* Modified sanitization rules for catalog descriptions:
* `<u>` tags are now transformed to `<em>`
* `<p>` tags within `<li>`s are removed
* `<sup>` and `<sub>` tags are …
> Full Catalog Processing and Formatting

- research/serializers.py
- research/urls.py
- research/views.py
- urls.py
Enhancements:
* Added 2 API views:
* ResearcherView: Provides teledata, biographical information and education data for each researcher within our system. In addition it links out to the ResearchWorks of the researcher.
* ResearchWorkView: Provides details of ResearchWorks for one research (specified by the ID).
> Research apis

- research/admin.py
- research/management/commands/orcid-meta-import.py
- research/management/commands/orcid-researcher-import.py
Bug Fixes:
* Updated logic so that staff members that have more than one entry in teledata get picked up.
* Fixed a bug where the bibtex from the previous record in the import gets written when there is no bibtex string
* Updated the admin screens to make finding research from particular researchers easier.
> Updated researcher importer and a few lingering bugs

- research/models.py
- research/serializers.py
Enhancements:
* Removed a number of properties no longer needed, and added a few new useful ones.
> Helper Properties!

- archimedes/package-lock.json
- archimedes/package.json
- package-lock.json
- package.json
Bug Fixes:
* Updates the core and archimedes javascript packages and closes the following dependabot pull requests:
* #237 
* #236 
* #231 
* #230 
* #229 
* #228 
* #227 
* #225
* #219
* #218 
* #213 
* #211 
* #208
> Updated js packages in core and archimedes

- research/models.py
- research/serializers.py
Enhancements:
* Adds the `featured_works_count` property to the `Researcher` model which gets a count of books and journal articles that have citation for the researcher.
* Added the new property to the API output.
> Added `featured_works_count` Property

- programs/management/commands/import-cip.py
Bug Fixes:
* NCES has updated the schema they use on the CIP export, so we needed to update our importer to match.
> CIP Importer Updated

- programs/utilities/catalog_match.py
- Moved Licensure Disclosure notes to the short program description (if present), and removed the incorrect heading above it
- Added "This program may be completed fully online..." blurb to the short program description, if present
- Commented all the things
> Catalog import - short description updates

- units/admin.py
Enhancements:
* Makes a few small changes to the admin interface for `units::Department` and `units::College` to account for multiple entries per field.
> Admin Interface Updates

- programs/models.py
- programs/serializers.py
Added `name` property to Program Colleges and Departments that returns a mapped Unit College/Department's `name` if set, or the object's `full_name` as a fallback.
> Added `name` property to Program Colleges, Departments

- requirements.txt
- setup.py
Bug Fixes:
* Updated Django and Pillow.
> Updated pillow and django

- programs/models.py
Enhancements:
* Removes the space between the last word in the excerpt and the ellipses.
> Remove the space between the ellipses and last word

- dev-requirements.txt
- pyproject.toml
- requirements.txt
Updates:
* Updates all packages to their newest compatible version.
* Resolves #366, #365, #364, #363, #350, #344, #332
> Updated all packages

- programs/utilities/catalog_match.py
Bug Fixes:
* The `prerequisiteAdmissionUg` section needs a header.
> Added header to program prerequisite section

- programs/management/commands/import-programs.py
Enhancements:
* Updated import logic to add "Undergraduate Certificate", "Graduate Certificate" or "Minor" to the end of programs when applicable.
> Degree Name Updates

- programs/management/commands/import-catalog-descriptions.py
Enhancements:
* Implemented paging while retrieving Kuali results to ease the load on the Kuali servers. Due to an inaccuracy in the total count of records coming back from Kuali, I had to implement an inventive way of ensuring we loop through all the pages, utilizing a loop with a couple of specific break criteria and an emergency break statement to ensure it doesn't loop infinitely.
> Kuali Paging

- core/models.py
- core/views.py
- templates/dashboard/home.html
Enhancements:
* Added more context data for dashboard view to replace placeholder data.
* Note: The career paths value is now pointing to a property on the extended user model, but the value of 22 is still hard coded. This will be updated once I've made the updates to the career path models.
> Additional context data Dashboard View

- core/templatetags/core_extras.py
- core/views.py
- templates/dashboard/home.html
Bug Fixes:
* Updates the dashboard view to make sure an ProgramImportRecord exists before trying to access the data within it.
> Import Record Bug Fix

- templates/dashboard/home.html
Enhancements:
* Made the missing jobs link work correctly
> Updated the missing jobs link in the dashboard

- core/models.py
- core/views.py
- src/scss/_ucf-header.scss
- templates/dashboard/home.html
Enhancements:
* Added styles to have collapsible activity lists on the dashboard.
* Corrected a bug where users with only colleges or departments have no programs.
> Activity rollup

- core/views.py
Bug Fixes:
* Fixes an error that gets thrown when programs are first imported that prevents the edit view in the dashboard from working.
> Added exception catching to fetching job data

- programs/models.py
> Added hook to ensure audit data gets added on program create

- core/models.py
- core/templatetags/core_extras.py
- core/views.py
- programs/models.py
- templates/dashboard/home.html
- templates/dashboard/usage-report.html
Enhancements:
* Added auditing for Program jobs. This causes an AuditLog entry to be created each time the jobs ManyToMany field is updated.
* Updated the usage report to be a single table that lists description created, descriptions updated, programs that have had jobs updated, and programs that have had highlights updated.
* Updated the home page activity logs to show only one entry per program.
* Added a link to the usage page on the activity logs.
> Jobs Audit Data and Usage Report Update

- templates/dashboard/program-edit.html
Added the feature to close the modal after the user select an Icon.
> Closing modal

- core/forms.py
Bug Fixes:
* Make the jobs field not required, as this is a many to many field and can be left blank.
> Jobs are not required. Everyone eats for free

- core/utils/jobs_utils.py
- core/views.py
- settings.py
- settings_local.tmpl.py
1. Cache logic was added to the view.
2. Created a utils directory and transferred the caching logic there.
3. Added limit and offset query parameters to the logic, which will be applied after the cache behavior.
Tested on local environment.
> Caching jobs

- programs/management/commands/import-profiles.py
Bug Fixes:
* Corrects a logic bug that caused the import to crash whenever it processed a degree that didn't have a plan_code assigned.
> Profile Importer Bug Fix

- core/views.py
Updated the logic in the career paths saving logic of the Communicator Dashboard to ensure consistent saving of data.
> Career Paths - Fix

- programs/management/commands/import-catalog-descriptions.py
Adds a small bit of logic that makes sure the newest catalog entry gets pulled in.
> Catalog Import Update

- marketing/models.py
By adding that regex, we wrap the first part of the title inside a <strong> tag. It is sensitive to commas — if no comma is provided, the entire title will be wrapped in the <strong> tag.
> added the logic to put the first part of title inside the <strong> tag

- core/storage_backends.py
- pyproject.toml
- requirements.txt
- settings_local.tmpl.py
- uv.lock
- Adds the necessary packages and logic to support S3 uploads for user media files.
> Added logic to support s3 uploads

- programs/management/commands/import-catalog-descriptions.py
Bug Fixes:
- Temporary bug fix to make sure only the main catalogs get pulled in. There is currently an "alternative" catalog listed that was getting pulled in instead of the primary graduate catalog.
- Tracking undergraduate and graduate matches and displaying that information so we have better visibility into issues like the one described above in the future.
- Running an additional filtering function on programs data that attempts to pull only the "latest" version of a program's catalog description.
> Added logic to ensure the latest catalog entries get pulled
